DROP PROCEDURE DB2JSON.DB2PROC;

CREATE PROCEDURE DB2JSON.DB2PROC(
INOUT PGMTMPL BLOB(15M)) 
LANGUAGE C NOT DETERMINISTIC 
MODIFIES SQL DATA 
EXTERNAL NAME 'DB2JSON/DB2PROC(iCall400)' 
PARAMETER STYLE GENERAL;

