#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <dlfcn.h>
#include <sqlcli1.h>
#include <as400_types.h>
#include <as400_protos.h>
#include "PaseCliInit.h"
#include "PaseCliAsync.h"

SQLRETURN (*libdb400_SQLAllocConnect)( SQLHENV, SQLHDBC* );
SQLRETURN (*libdb400_SQLAllocEnv)( SQLHENV* );
SQLRETURN (*libdb400_SQLAllocHandle)( SQLSMALLINT, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLAllocStmt)( SQLHDBC, SQLHSTMT* );
SQLRETURN (*libdb400_SQLBindCol)( SQLHSTMT, SQLSMALLINT, SQLSMALLINT, SQLPOINTER, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLBindFileToCol)( SQLHSTMT, SQLSMALLINT, SQLCHAR*, SQLSMALLINT*, SQLINTEGER*, SQLSMALLINT, SQLINTEGER*, SQLINTEGER* );
SQLRETURN (*libdb400_SQLBindFileToParam)( SQLHSTMT, SQLSMALLINT, SQLSMALLINT, SQLCHAR*, SQLSMALLINT*, SQLINTEGER*, SQLSMALLINT, SQLINTEGER* );
SQLRETURN (*libdb400_SQLBindParam)( SQLHSTMT, SQLSMALLINT, SQLSMALLINT, SQLSMALLINT, SQLINTEGER, SQLSMALLINT, SQLPOINTER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLBindParameter)( SQLHSTMT, SQLSMALLINT, SQLSMALLINT, SQLSMALLINT, SQLSMALLINT, SQLINTEGER, SQLSMALLINT, SQLPOINTER, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLCancel)( SQLHSTMT );
SQLRETURN (*libdb400_SQLCloseCursor)( SQLHSTMT );
SQLRETURN (*libdb400_SQLColAttribute)( SQLHSTMT, SQLSMALLINT, SQLSMALLINT, SQLPOINTER, SQLSMALLINT, SQLSMALLINT*, SQLPOINTER );
SQLRETURN (*libdb400_SQLColAttributeW)( SQLHSTMT, SQLSMALLINT, SQLSMALLINT, SQLPOINTER, SQLSMALLINT, SQLSMALLINT*, SQLPOINTER );
SQLRETURN (*libdb400_SQLColAttributes)( SQLHSTMT, SQLSMALLINT, SQLSMALLINT, SQLCHAR*, SQLINTEGER, SQLINTEGER*, SQLINTEGER* );
SQLRETURN (*libdb400_SQLColAttributesW)( SQLHSTMT, SQLSMALLINT, SQLSMALLINT, SQLWCHAR*, SQLINTEGER, SQLINTEGER*, SQLINTEGER* );
SQLRETURN (*libdb400_SQLColumnPrivileges)( SQLHSTMT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLColumnPrivilegesW)( SQLHSTMT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLColumns)( SQLHSTMT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLColumnsW)( SQLHSTMT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLConnect)( SQLHDBC, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLConnectW)( SQLHDBC, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLCopyDesc)( SQLHDESC, SQLHDESC );
SQLRETURN (*libdb400_SQLDataSources)( SQLHENV, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLSMALLINT*, SQLCHAR*, SQLSMALLINT, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLDataSourcesW)( SQLHENV, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLSMALLINT*, SQLWCHAR*, SQLSMALLINT, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLDescribeCol)( SQLHSTMT, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLSMALLINT*, SQLSMALLINT*, SQLINTEGER*, SQLSMALLINT*, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLDescribeColW)( SQLHSTMT, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLSMALLINT*, SQLSMALLINT*, SQLINTEGER*, SQLSMALLINT*, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLDescribeParam)( SQLHSTMT, SQLSMALLINT, SQLSMALLINT*, SQLINTEGER*, SQLSMALLINT*, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLDisconnect)( SQLHDBC );
SQLRETURN (*libdb400_SQLDriverConnect)( SQLHDBC, SQLPOINTER, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLSMALLINT*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLDriverConnectW)( SQLHDBC, SQLPOINTER, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLSMALLINT*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLEndTran)( SQLSMALLINT, SQLHENV, SQLSMALLINT );
SQLRETURN (*libdb400_SQLError)( SQLHENV, SQLHDBC, SQLHSTMT, SQLCHAR*, SQLINTEGER*, SQLCHAR*, SQLSMALLINT, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLErrorW)( SQLHENV, SQLHDBC, SQLHSTMT, SQLWCHAR*, SQLINTEGER*, SQLWCHAR*, SQLSMALLINT, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLExecDirect)( SQLHSTMT, SQLCHAR*, SQLINTEGER );
SQLRETURN (*libdb400_SQLExecDirectW)( SQLHSTMT, SQLWCHAR*, SQLINTEGER );
SQLRETURN (*libdb400_SQLExecute)( SQLHSTMT );
SQLRETURN (*libdb400_SQLExtendedFetch)( SQLHSTMT, SQLSMALLINT, SQLINTEGER, SQLINTEGER*, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLFetch)( SQLHSTMT );
SQLRETURN (*libdb400_SQLFetchScroll)( SQLHSTMT, SQLSMALLINT, SQLINTEGER );
SQLRETURN (*libdb400_SQLForeignKeys)( SQLHSTMT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLForeignKeysW)( SQLHSTMT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLFreeConnect)( SQLHDBC );
SQLRETURN (*libdb400_SQLFreeEnv)( SQLHENV );
SQLRETURN (*libdb400_SQLFreeStmt)( SQLHSTMT, SQLSMALLINT );
SQLRETURN (*libdb400_SQLFreeHandle)( SQLSMALLINT, SQLINTEGER );
SQLRETURN (*libdb400_SQLGetCol)( SQLHSTMT, SQLSMALLINT, SQLSMALLINT, SQLPOINTER, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLGetColW)( SQLHSTMT, SQLSMALLINT, SQLSMALLINT, SQLPOINTER, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLGetConnectAttr)( SQLHDBC, SQLINTEGER, SQLPOINTER, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLGetConnectAttrW)( SQLHDBC, SQLINTEGER, SQLPOINTER, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLGetConnectOption)( SQLHDBC, SQLSMALLINT, SQLPOINTER );
SQLRETURN (*libdb400_SQLGetConnectOptionW)( SQLHDBC, SQLSMALLINT, SQLPOINTER );
SQLRETURN (*libdb400_SQLGetCursorName)( SQLHSTMT, SQLCHAR*, SQLSMALLINT, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLGetCursorNameW)( SQLHSTMT, SQLWCHAR*, SQLSMALLINT, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLGetData)( SQLHSTMT, SQLSMALLINT, SQLSMALLINT, SQLPOINTER, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLGetDescField)( SQLHDESC, SQLSMALLINT, SQLSMALLINT, SQLPOINTER, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLGetDescFieldW)( SQLHDESC, SQLSMALLINT, SQLSMALLINT, SQLPOINTER, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLGetDescRec)( SQLHDESC, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLSMALLINT*, SQLSMALLINT*, SQLSMALLINT*, SQLINTEGER*, SQLSMALLINT*, SQLSMALLINT*, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLGetDescRecW)( SQLHDESC, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLSMALLINT*, SQLSMALLINT*, SQLSMALLINT*, SQLINTEGER*, SQLSMALLINT*, SQLSMALLINT*, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLGetDiagField)( SQLSMALLINT, SQLINTEGER, SQLSMALLINT, SQLSMALLINT, SQLPOINTER, SQLSMALLINT, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLGetDiagFieldW)( SQLSMALLINT, SQLINTEGER, SQLSMALLINT, SQLSMALLINT, SQLPOINTER, SQLSMALLINT, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLGetDiagRec)( SQLSMALLINT, SQLINTEGER, SQLSMALLINT, SQLCHAR*, SQLINTEGER*, SQLCHAR*, SQLSMALLINT, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLGetDiagRecW)( SQLSMALLINT, SQLINTEGER, SQLSMALLINT, SQLWCHAR*, SQLINTEGER*, SQLWCHAR*, SQLSMALLINT, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLGetEnvAttr)( SQLHENV, SQLINTEGER, SQLPOINTER, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLGetFunctions)( SQLHDBC, SQLSMALLINT, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLGetInfo)( SQLHDBC, SQLSMALLINT, SQLPOINTER, SQLSMALLINT, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLGetInfoW)( SQLHDBC, SQLSMALLINT, SQLPOINTER, SQLSMALLINT, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLGetLength)( SQLHSTMT, SQLSMALLINT, SQLINTEGER, SQLINTEGER*, SQLINTEGER* );
SQLRETURN (*libdb400_SQLGetPosition)( SQLHSTMT, SQLSMALLINT, SQLINTEGER, SQLINTEGER, SQLCHAR*, SQLINTEGER, SQLINTEGER, SQLINTEGER*, SQLINTEGER* );
SQLRETURN (*libdb400_SQLGetPositionW)( SQLHSTMT, SQLSMALLINT, SQLINTEGER, SQLINTEGER, SQLWCHAR*, SQLINTEGER, SQLINTEGER, SQLINTEGER*, SQLINTEGER* );
SQLRETURN (*libdb400_SQLGetStmtAttr)( SQLHSTMT, SQLINTEGER, SQLPOINTER, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLGetStmtAttrW)( SQLHSTMT, SQLINTEGER, SQLPOINTER, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLGetStmtOption)( SQLHSTMT, SQLSMALLINT, SQLPOINTER );
SQLRETURN (*libdb400_SQLGetStmtOptionW)( SQLHSTMT, SQLSMALLINT, SQLPOINTER );
SQLRETURN (*libdb400_SQLGetSubString)( SQLHSTMT, SQLSMALLINT, SQLINTEGER, SQLINTEGER, SQLINTEGER, SQLSMALLINT, SQLPOINTER, SQLINTEGER, SQLINTEGER*, SQLINTEGER* );
SQLRETURN (*libdb400_SQLGetSubStringW)( SQLHSTMT, SQLSMALLINT, SQLINTEGER, SQLINTEGER, SQLINTEGER, SQLSMALLINT, SQLPOINTER, SQLINTEGER, SQLINTEGER*, SQLINTEGER* );
SQLRETURN (*libdb400_SQLGetTypeInfo)( SQLHSTMT, SQLSMALLINT );
SQLRETURN (*libdb400_SQLGetTypeInfoW)( SQLHSTMT, SQLSMALLINT );
SQLRETURN (*libdb400_SQLLanguages)( SQLHSTMT );
SQLRETURN (*libdb400_SQLMoreResults)( SQLHSTMT );
SQLRETURN (*libdb400_SQLNativeSql)( SQLHDBC, SQLCHAR*, SQLINTEGER, SQLCHAR*, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLNativeSqlW)( SQLHDBC, SQLWCHAR*, SQLINTEGER, SQLWCHAR*, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLNextResult)( SQLHSTMT, SQLHSTMT );
SQLRETURN (*libdb400_SQLNumParams)( SQLHSTMT, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLNumResultCols)( SQLHSTMT, SQLSMALLINT* );
SQLRETURN (*libdb400_SQLParamData)( SQLHSTMT, SQLPOINTER* );
SQLRETURN (*libdb400_SQLParamOptions)( SQLHSTMT, SQLINTEGER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLPrepare)( SQLHSTMT, SQLCHAR*, SQLINTEGER );
SQLRETURN (*libdb400_SQLPrepareW)( SQLHSTMT, SQLWCHAR*, SQLINTEGER );
SQLRETURN (*libdb400_SQLPrimaryKeys)( SQLHSTMT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLPrimaryKeysW)( SQLHSTMT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLProcedureColumns)( SQLHSTMT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLProcedureColumnsW)( SQLHSTMT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLProcedures)( SQLHSTMT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLProceduresW)( SQLHSTMT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLPutData)( SQLHSTMT, SQLPOINTER, SQLINTEGER );
SQLRETURN (*libdb400_SQLReleaseEnv)( SQLHENV );
SQLRETURN (*libdb400_SQLRowCount)( SQLHSTMT, SQLINTEGER* );
SQLRETURN (*libdb400_SQLSetConnectAttr)( SQLHDBC, SQLINTEGER, SQLPOINTER, SQLINTEGER );
SQLRETURN (*libdb400_SQLSetConnectAttrW)( SQLHDBC, SQLINTEGER, SQLPOINTER, SQLINTEGER );
SQLRETURN (*libdb400_SQLSetConnectOption)( SQLHDBC, SQLSMALLINT, SQLPOINTER );
SQLRETURN (*libdb400_SQLSetConnectOptionW)( SQLHDBC, SQLSMALLINT, SQLPOINTER );
SQLRETURN (*libdb400_SQLSetCursorName)( SQLHSTMT, SQLCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLSetCursorNameW)( SQLHSTMT, SQLWCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLSetDescField)( SQLHDESC, SQLSMALLINT, SQLSMALLINT, SQLPOINTER, SQLINTEGER );
SQLRETURN (*libdb400_SQLSetDescFieldW)( SQLHDESC, SQLSMALLINT, SQLSMALLINT, SQLPOINTER, SQLINTEGER );
SQLRETURN (*libdb400_SQLSetDescRec)( SQLHDESC, SQLSMALLINT, SQLSMALLINT, SQLSMALLINT, SQLINTEGER, SQLSMALLINT, SQLSMALLINT, SQLPOINTER, SQLINTEGER*, SQLINTEGER* );
SQLRETURN (*libdb400_SQLSetEnvAttr)( SQLHENV, SQLINTEGER, SQLPOINTER, SQLINTEGER );
SQLRETURN (*libdb400_SQLSetParam)( SQLHSTMT, SQLSMALLINT, SQLSMALLINT, SQLSMALLINT, SQLINTEGER, SQLSMALLINT, SQLPOINTER, SQLINTEGER* );
SQLRETURN (*libdb400_SQLSetStmtAttr)( SQLHSTMT, SQLINTEGER, SQLPOINTER, SQLINTEGER );
SQLRETURN (*libdb400_SQLSetStmtAttrW)( SQLHSTMT, SQLINTEGER, SQLPOINTER, SQLINTEGER );
SQLRETURN (*libdb400_SQLSetStmtOption)( SQLHSTMT, SQLSMALLINT, SQLPOINTER );
SQLRETURN (*libdb400_SQLSetStmtOptionW)( SQLHSTMT, SQLSMALLINT, SQLPOINTER );
SQLRETURN (*libdb400_SQLSpecialColumns)( SQLHSTMT, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLSMALLINT, SQLSMALLINT );
SQLRETURN (*libdb400_SQLSpecialColumnsW)( SQLHSTMT, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLSMALLINT, SQLSMALLINT );
SQLRETURN (*libdb400_SQLStartTran)( SQLSMALLINT, SQLHENV, SQLINTEGER, SQLINTEGER );
SQLRETURN (*libdb400_SQLStatistics)( SQLHSTMT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLSMALLINT, SQLSMALLINT );
SQLRETURN (*libdb400_SQLStatisticsW)( SQLHSTMT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLSMALLINT, SQLSMALLINT );
SQLRETURN (*libdb400_SQLTablePrivileges)( SQLHSTMT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLTablePrivilegesW)( SQLHSTMT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLTables)( SQLHSTMT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT, SQLCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLTablesW)( SQLHSTMT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT, SQLWCHAR*, SQLSMALLINT );
SQLRETURN (*libdb400_SQLTransact)( SQLHENV, SQLHDBC, SQLSMALLINT );


void libdb400_load_dlsym() {
  libdb400_SQLAllocConnect = dlsym(dlhandle, "SQLAllocConnect");
  libdb400_SQLAllocEnv = dlsym(dlhandle, "SQLAllocEnv");
  libdb400_SQLAllocHandle = dlsym(dlhandle, "SQLAllocHandle");
  libdb400_SQLAllocStmt = dlsym(dlhandle, "SQLAllocStmt");
  libdb400_SQLBindCol = dlsym(dlhandle, "SQLBindCol");
  libdb400_SQLBindFileToCol = dlsym(dlhandle, "SQLBindFileToCol");
  libdb400_SQLBindFileToParam = dlsym(dlhandle, "SQLBindFileToParam");
  libdb400_SQLBindParam = dlsym(dlhandle, "SQLBindParam");
  libdb400_SQLBindParameter = dlsym(dlhandle, "SQLBindParameter");
  libdb400_SQLCancel = dlsym(dlhandle, "SQLCancel");
  libdb400_SQLCloseCursor = dlsym(dlhandle, "SQLCloseCursor");
  libdb400_SQLColAttribute = dlsym(dlhandle, "SQLColAttribute");
  libdb400_SQLColAttributeW = dlsym(dlhandle, "SQLColAttributeW");
  libdb400_SQLColAttributes = dlsym(dlhandle, "SQLColAttributes");
  libdb400_SQLColAttributesW = dlsym(dlhandle, "SQLColAttributesW");
  libdb400_SQLColumnPrivileges = dlsym(dlhandle, "SQLColumnPrivileges");
  libdb400_SQLColumnPrivilegesW = dlsym(dlhandle, "SQLColumnPrivilegesW");
  libdb400_SQLColumns = dlsym(dlhandle, "SQLColumns");
  libdb400_SQLColumnsW = dlsym(dlhandle, "SQLColumnsW");
  libdb400_SQLConnect = dlsym(dlhandle, "SQLConnect");
  libdb400_SQLConnectW = dlsym(dlhandle, "SQLConnectW");
  libdb400_SQLCopyDesc = dlsym(dlhandle, "SQLCopyDesc");
  libdb400_SQLDataSources = dlsym(dlhandle, "SQLDataSources");
  libdb400_SQLDataSourcesW = dlsym(dlhandle, "SQLDataSourcesW");
  libdb400_SQLDescribeCol = dlsym(dlhandle, "SQLDescribeCol");
  libdb400_SQLDescribeColW = dlsym(dlhandle, "SQLDescribeColW");
  libdb400_SQLDescribeParam = dlsym(dlhandle, "SQLDescribeParam");
  libdb400_SQLDisconnect = dlsym(dlhandle, "SQLDisconnect");
  libdb400_SQLDriverConnect = dlsym(dlhandle, "SQLDriverConnect");
  libdb400_SQLDriverConnectW = dlsym(dlhandle, "SQLDriverConnectW");
  libdb400_SQLEndTran = dlsym(dlhandle, "SQLEndTran");
  libdb400_SQLError = dlsym(dlhandle, "SQLError");
  libdb400_SQLErrorW = dlsym(dlhandle, "SQLErrorW");
  libdb400_SQLExecDirect = dlsym(dlhandle, "SQLExecDirect");
  libdb400_SQLExecDirectW = dlsym(dlhandle, "SQLExecDirectW");
  libdb400_SQLExecute = dlsym(dlhandle, "SQLExecute");
  libdb400_SQLExtendedFetch = dlsym(dlhandle, "SQLExtendedFetch");
  libdb400_SQLFetch = dlsym(dlhandle, "SQLFetch");
  libdb400_SQLFetchScroll = dlsym(dlhandle, "SQLFetchScroll");
  libdb400_SQLForeignKeys = dlsym(dlhandle, "SQLForeignKeys");
  libdb400_SQLForeignKeysW = dlsym(dlhandle, "SQLForeignKeysW");
  libdb400_SQLFreeConnect = dlsym(dlhandle, "SQLFreeConnect");
  libdb400_SQLFreeEnv = dlsym(dlhandle, "SQLFreeEnv");
  libdb400_SQLFreeStmt = dlsym(dlhandle, "SQLFreeStmt");
  libdb400_SQLFreeHandle = dlsym(dlhandle, "SQLFreeHandle");
  libdb400_SQLGetCol = dlsym(dlhandle, "SQLGetCol");
  libdb400_SQLGetColW = dlsym(dlhandle, "SQLGetColW");
  libdb400_SQLGetConnectAttr = dlsym(dlhandle, "SQLGetConnectAttr");
  libdb400_SQLGetConnectAttrW = dlsym(dlhandle, "SQLGetConnectAttrW");
  libdb400_SQLGetConnectOption = dlsym(dlhandle, "SQLGetConnectOption");
  libdb400_SQLGetConnectOptionW = dlsym(dlhandle, "SQLGetConnectOptionW");
  libdb400_SQLGetCursorName = dlsym(dlhandle, "SQLGetCursorName");
  libdb400_SQLGetCursorNameW = dlsym(dlhandle, "SQLGetCursorNameW");
  libdb400_SQLGetData = dlsym(dlhandle, "SQLGetData");
  libdb400_SQLGetDescField = dlsym(dlhandle, "SQLGetDescField");
  libdb400_SQLGetDescFieldW = dlsym(dlhandle, "SQLGetDescFieldW");
  libdb400_SQLGetDescRec = dlsym(dlhandle, "SQLGetDescRec");
  libdb400_SQLGetDescRecW = dlsym(dlhandle, "SQLGetDescRecW");
  libdb400_SQLGetDiagField = dlsym(dlhandle, "SQLGetDiagField");
  libdb400_SQLGetDiagFieldW = dlsym(dlhandle, "SQLGetDiagFieldW");
  libdb400_SQLGetDiagRec = dlsym(dlhandle, "SQLGetDiagRec");
  libdb400_SQLGetDiagRecW = dlsym(dlhandle, "SQLGetDiagRecW");
  libdb400_SQLGetEnvAttr = dlsym(dlhandle, "SQLGetEnvAttr");
  libdb400_SQLGetFunctions = dlsym(dlhandle, "SQLGetFunctions");
  libdb400_SQLGetInfo = dlsym(dlhandle, "SQLGetInfo");
  libdb400_SQLGetInfoW = dlsym(dlhandle, "SQLGetInfoW");
  libdb400_SQLGetLength = dlsym(dlhandle, "SQLGetLength");
  libdb400_SQLGetPosition = dlsym(dlhandle, "SQLGetPosition");
  libdb400_SQLGetPositionW = dlsym(dlhandle, "SQLGetPositionW");
  libdb400_SQLGetStmtAttr = dlsym(dlhandle, "SQLGetStmtAttr");
  libdb400_SQLGetStmtAttrW = dlsym(dlhandle, "SQLGetStmtAttrW");
  libdb400_SQLGetStmtOption = dlsym(dlhandle, "SQLGetStmtOption");
  libdb400_SQLGetStmtOptionW = dlsym(dlhandle, "SQLGetStmtOptionW");
  libdb400_SQLGetSubString = dlsym(dlhandle, "SQLGetSubString");
  libdb400_SQLGetSubStringW = dlsym(dlhandle, "SQLGetSubStringW");
  libdb400_SQLGetTypeInfo = dlsym(dlhandle, "SQLGetTypeInfo");
  libdb400_SQLGetTypeInfoW = dlsym(dlhandle, "SQLGetTypeInfoW");
  libdb400_SQLLanguages = dlsym(dlhandle, "SQLLanguages");
  libdb400_SQLMoreResults = dlsym(dlhandle, "SQLMoreResults");
  libdb400_SQLNativeSql = dlsym(dlhandle, "SQLNativeSql");
  libdb400_SQLNativeSqlW = dlsym(dlhandle, "SQLNativeSqlW");
  libdb400_SQLNextResult = dlsym(dlhandle, "SQLNextResult");
  libdb400_SQLNumParams = dlsym(dlhandle, "SQLNumParams");
  libdb400_SQLNumResultCols = dlsym(dlhandle, "SQLNumResultCols");
  libdb400_SQLParamData = dlsym(dlhandle, "SQLParamData");
  libdb400_SQLParamOptions = dlsym(dlhandle, "SQLParamOptions");
  libdb400_SQLPrepare = dlsym(dlhandle, "SQLPrepare");
  libdb400_SQLPrepareW = dlsym(dlhandle, "SQLPrepareW");
  libdb400_SQLPrimaryKeys = dlsym(dlhandle, "SQLPrimaryKeys");
  libdb400_SQLPrimaryKeysW = dlsym(dlhandle, "SQLPrimaryKeysW");
  libdb400_SQLProcedureColumns = dlsym(dlhandle, "SQLProcedureColumns");
  libdb400_SQLProcedureColumnsW = dlsym(dlhandle, "SQLProcedureColumnsW");
  libdb400_SQLProcedures = dlsym(dlhandle, "SQLProcedures");
  libdb400_SQLProceduresW = dlsym(dlhandle, "SQLProceduresW");
  libdb400_SQLPutData = dlsym(dlhandle, "SQLPutData");
  libdb400_SQLReleaseEnv = dlsym(dlhandle, "SQLReleaseEnv");
  libdb400_SQLRowCount = dlsym(dlhandle, "SQLRowCount");
  libdb400_SQLSetConnectAttr = dlsym(dlhandle, "SQLSetConnectAttr");
  libdb400_SQLSetConnectAttrW = dlsym(dlhandle, "SQLSetConnectAttrW");
  libdb400_SQLSetConnectOption = dlsym(dlhandle, "SQLSetConnectOption");
  libdb400_SQLSetConnectOptionW = dlsym(dlhandle, "SQLSetConnectOptionW");
  libdb400_SQLSetCursorName = dlsym(dlhandle, "SQLSetCursorName");
  libdb400_SQLSetCursorNameW = dlsym(dlhandle, "SQLSetCursorNameW");
  libdb400_SQLSetDescField = dlsym(dlhandle, "SQLSetDescField");
  libdb400_SQLSetDescFieldW = dlsym(dlhandle, "SQLSetDescFieldW");
  libdb400_SQLSetDescRec = dlsym(dlhandle, "SQLSetDescRec");
  libdb400_SQLSetEnvAttr = dlsym(dlhandle, "SQLSetEnvAttr");
  libdb400_SQLSetParam = dlsym(dlhandle, "SQLSetParam");
  libdb400_SQLSetStmtAttr = dlsym(dlhandle, "SQLSetStmtAttr");
  libdb400_SQLSetStmtAttrW = dlsym(dlhandle, "SQLSetStmtAttrW");
  libdb400_SQLSetStmtOption = dlsym(dlhandle, "SQLSetStmtOption");
  libdb400_SQLSetStmtOptionW = dlsym(dlhandle, "SQLSetStmtOptionW");
  libdb400_SQLSpecialColumns = dlsym(dlhandle, "SQLSpecialColumns");
  libdb400_SQLSpecialColumnsW = dlsym(dlhandle, "SQLSpecialColumnsW");
  libdb400_SQLStartTran = dlsym(dlhandle, "SQLStartTran");
  libdb400_SQLStatistics = dlsym(dlhandle, "SQLStatistics");
  libdb400_SQLStatisticsW = dlsym(dlhandle, "SQLStatisticsW");
  libdb400_SQLTablePrivileges = dlsym(dlhandle, "SQLTablePrivileges");
  libdb400_SQLTablePrivilegesW = dlsym(dlhandle, "SQLTablePrivilegesW");
  libdb400_SQLTables = dlsym(dlhandle, "SQLTables");
  libdb400_SQLTablesW = dlsym(dlhandle, "SQLTablesW");
  libdb400_SQLTransact = dlsym(dlhandle, "SQLTransact");

}

