#!/opt/freeware/bin/python
# syntax: 
#   pdbx '-a pid'
#   pdbx mypgm
import sys, os, time, fcntl
import subprocess
proc = subprocess.Popen(['dbx','-d 100','-I .','-I ..',sys.argv[1]], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
proc.stdin.write("dbx\n")
while True:
  isread = False
  nextline = proc.stdout.readline()
  if nextline == '' and proc.poll() is not None:
    break
  if 'internal error' in nextline:
    continue
  if "unrecognized" in nextline:
    isread = True
    nextline = ""
  sys.stdout.write(nextline)
  sys.stdout.flush()
  time.sleep(0.05)
  if isread:
    line = raw_input("> ")
    proc.stdin.write(line)
    proc.stdin.write("\n")
    proc.stdin.write("dbx\n")
