#!/bin/sh
root=$INICHROOT
here=$(pwd)
lib=$1
ifs=$2
mod=$(echo "$ifs" | cut -d'.' -f1 | cut -d'/' -f2)
touch "./$mod.mod"
arg="CRTCMOD MODULE($lib/$mod) SRCSTMF('$root$here/$ifs') DBGVIEW(*SOURCE) OUTPUT(*PRINT) REPLACE(*YES) TGTCCSID(37)"
echo "./system400 '$arg'"
RES=$(./system400 "$arg" $root)
OK=$(echo "$RES" | grep -c "was created in library")
if (($OK==0))
then
  echo "$RES"
  exit
else
  echo "==> $lib/$mod -- was created in library"
fi

