#!/bin/sh
pgm=$1
mods=""
OK=0
for arg in "$@"
{
  if (($OK==1))
  then
    mods="$mods $arg"
  fi
  OK=1
}
ppp=$(echo "$ifs" | cut -d'/' -f2)
touch "./$ppp.pgm"
arg="CRTPGM PGM($pgm) MODULE($mods) BNDSRVPGM(QHTTPSVR/QZSRCORE) ACTGRP(DB2JSON)"
echo "./system400 '$arg'"
./system400 "$arg" $root

